name: aishny_site_dev

services:
    app:
      build: ..
      ports:
        - "8002:8000"  # Dev работает на порту 8002
        - "8003:8001"  # RSS server на 8003
      env_file:
        - ../.env
      environment:
        SELENIUM_REMOTE_URL: http://selenium:4444/wd/hub
        NODE_TLS_REJECT_UNAUTHORIZED: "0"
      dns:
        - 8.8.8.8
        - 8.8.4.4
      volumes:
        - ../data:/app/data
        - ../etc:/app/etc
      depends_on:
        - selenium

    selenium:
      image: selenium/standalone-chromium:latest
      shm_size: "2gb"
      ports:
        - "4445:4444"  # Dev Selenium на другом порту
